### PR TITLE
Update join-mainnet.md guide

### PR DESCRIPTION
**Pull request by napelvs**
It's based on the `join-testnet.md` guide I've pushed as [a separate PR](https://github.com/persistenceOne/persistence-docs/pull/12). There are slight changes to accommodate running the node on the core-1 chain instead of the test-core-1 chain.

### CODE REVIEW

**Review by ajeet97 — CHANGES_REQUESTED** [review]
Changes mentioned in https://github.com/persistenceOne/persistence-docs/pull/13 can be made here as well.

Also change the `{% hint %}` messages accordingly as well.

**Comment by napelvs** [comment]
> Changes mentioned in #13 can be made here as well.
> 
> Also change the `{% hint %}` messages accordingly as well.

@ajeet97 I'll need the seed address for mainnet.

**Comment by ajeet97** [comment]
> @ajeet97 I'll need the seed address for mainnet.

You can find it here https://www.allthatnode.com/persistence.dsrv

**Review by ajeet97 — APPROVED** [review]
LGTM

**Pull request merged**
